name: Build Calculator APK

on:
  push:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install Java and tools
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            git \
            zip \
            unzip \
            openjdk-17-jdk


      - name: Install Buildozer
        run: |
          pip install --user buildozer cython


      - name: Prepare Android SDK licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true


      - name: Install Android SDK packages
        run: |
          sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"


      - name: Build APK
        run: |
          buildozer android debug


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: advanced-calculator-apk
          path: bin/*.apk
