name: Build Calculator APK

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk


      - name: Install Buildozer
        run: |
          pip install --user buildozer cython


      - name: First Buildozer setup
        run: |
          buildozer android debug || true


      - name: Accept Buildozer Android licenses
        run: |
          SDK="$HOME/.buildozer/android/platform/android-sdk"

          yes | "$SDK/cmdline-tools/latest/bin/sdkmanager" --licenses || true

          "$SDK/cmdline-tools/latest/bin/sdkmanager" \
          "platform-tools" \
          "platforms;android-35" \
          "build-tools;35.0.0"


      - name: Build APK
        run: |
          buildozer android debug


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
